format = '''
[➜ ](bold green)$directory$git_branch'''


[directory]
home_symbol = '~'
truncation_length = 1
truncation_symbol = ''
style = 'bold red'

[time]
disabled = false
format = '[ $time](bold blue)'
time_format = '%T'
utc_time_offset = 'local'

[git_branch]
symbol = ''
truncation_length = 4
truncation_symbol = ''
