format = '''
[➜ ](bold green)$directory$git_branch[](bold yellow) '''


[directory]
home_symbol = '~'
truncation_length = 1
truncation_symbol = ''
style = 'bold cyan'

[time]
disabled = false
format = '[ $time](bold blue)'
time_format = '%T'
utc_time_offset = 'local'

[git_branch]
format = '[git:\(](bold blue)[($branch)]($style)[\)](bold blue)'
symbol = ''
truncation_symbol = ''
style = 'bold red'
